//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerSTVietnamMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingDetail
    {
        public int DetailID { get; set; }
        public int ProductID { get; set; }
        public int InvoiceID { get; set; }
        public int Quantity { get; set; }
        public int SizeID { get; set; }
        public double SellPrice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
