//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerSTVietnamMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SlideID { get; set; }
        public string SlideName { get; set; }
        public string Slide_Description { get; set; }
        public string SlideLink { get; set; }
        public string SlideButtonName { get; set; }
        public string SliderImage { get; set; }
    }
}
